In [2]:
import pandas as pd
import numpy as np
import datetime

In [3]:
risk_factors = pd.read_csv("../data/number-of-deaths-by-risk-factor.csv")
risk_factors_df = pd.DataFrame(risk_factors)

In [4]:
risk_factors_df.head()

,Entity,Code,Year,Unsafe water source (deaths),Poor sanitation (deaths),No access to handwashing facility (deaths),Indoor air pollution (deaths),Non-exclusive breastfeeding (deaths),Discontinued breastfeeding (deaths),Child wasting (deaths),...,Air pollution (outdoor & indoor) (deaths),Outdoor air pollution (deaths),Diet low in fiber (deaths),Diet high in sodium (deaths),Diet low in legumes (deaths),Diet low in calcium (deaths),Diet high in red meat (deaths),Diet low in whole grains (deaths),Diet low in nuts and seeds (deaths),Diet low in seafood omega-3 fatty acids (deaths)
0,Afghanistan,AFG,1990,7554.049543,5887.747628,5412.314513,22388.497233,3221.138842,156.097553,22778.849249,...,26598.006727,4383.83,2864.234512,2737.197934,3418.965194,181.287701,0.220484,11381.377345,7299.867330,6456.565238
1,Afghanistan,AFG,1991,7359.676749,5732.770160,5287.891103,22128.758206,3150.559597,151.539851,22292.691113,...,26379.532218,4426.36,2974.479775,2741.184956,3457.398250,184.251584,0.184714,11487.832390,7386.764303,6511.344276
2,Afghanistan,AFG,1992,7650.437822,5954.804987,5506.657363,22873.768789,3331.349048,156.609194,23102.197940,...,27263.127914,4568.91,3168.591633,2798.560245,3586.490291,191.318450,0.151354,11866.235572,7640.628526,6703.095594
3,Afghanistan,AFG,1993,10270.731383,7986.736613,7104.620351,25599.756284,4477.006100,206.834451,27902.669960,...,30495.561499,5080.29,3401.045056,2853.301679,3746.266658,199.767293,0.109392,12335.961682,7968.311853,6946.196824
4,Afghanistan,AFG,1994,11409.177112,8863.010065,8051.515953,28013.167200,5102.622054,233.930571,32929.005932,...,33323.161401,5499.23,3599.709735,2880.025765,3869.288402,206.619714,0.059103,12672.950191,8244.368430,7138.030745

In [ ]:
entity = []
year = []
count = []
factor = []
code = []

# for i in range(0, len(bird_counts)-1):
#     species_total = 0
#     for j in range(2, len(bird_counts.columns)-2):        
#         year_value = str(bird_counts.iloc[i, j])
        
#         cp_substring = "CP"
#         if (cp_substring in year_value):
#             year_value = 0.0
#         else:
#             year_value = float(bird_counts.iloc[i, j])
#             if np.isnan(year_value):
#                 year_value = 0.0
                
#         bird_counts.iloc[i, j] = year_value
#         species_total = int(year_value) + species_total
    
for i in range(0, len(risk_factors)):
    for j in range(0, len(risk_factors.columns)):
        
        if (bird_counts.iloc[i, 1].strip() == "Total Individuals"):
            species.append("All Bird Species")
        elif(bird_counts.iloc[i, 1].strip() == "Yellow bellied Sapsucker"):
            species.append("Yellow-bellied sapsucker")
        elif(bird_counts.iloc[i, 1].strip() == "Thursh, Hermit"):
            species.append("Thrush, Hermit")
        elif(bird_counts.iloc[i, 1].strip() == "Woodpecker, Red Bellied"):
            species.append("Woodpecker, Red-bellied")
        else:
            species.append(bird_counts.iloc[i, 1].strip())
            
        species_index.append(i)
        
        x = datetime.datetime(int(bird_counts.columns[j]), 1, 1)
        
        year.append(x.strftime("%y"))
                    
        count.append(bird_counts.iloc[i, j])
    

bird_counts_dict = {"Species": species, "Year": year, "Count": count, "Species_Index": species_index}
bird_counts_df = pd.DataFrame(bird_counts_dict)

#bird_counts_df.to_csv('../data/bird_counts_edited_2020_03_21.csv')