In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
bird_counts = pd.read_csv("../data/CBC_2013_Tin_MTN.csv")
bird_counts = pd.DataFrame(bird_counts)

In [3]:
bird_counts.head(50)

,SPECIES,1989,1990,1991,1992,1993,1994,1995,1996,1997,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,"Heron, Great Blue",0.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"Goose, Canada",0.0,1,3,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,"Goose, Snow",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,5,0,0,0,0,0
3,"Duck,Wood",0.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"Duck, Mallard",6.0,4,40,72,49,85,53,32,63,...,180,57,22,67,137,29,75,25,18,51
5,"Duck, American Black",58.0,24,0,2,15,53,5,4,6,...,0,5,1,5,10,0,1,0,0,2
6,"Merganser, Hooded",2.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3
7,"Vulture, Turkey",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,"Eagle, Golden",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
9,"Eagle, Bald",0.0,0,0,0,0,0,0,0,0,...,0,2,1,1,3,1,0,1,1,0
10,"Harrier, Northern",0.0,0,0,0,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11,"Hawk, Sharp-shinned",0.0,0,1,2,0,0,0,0,2,...,2,2,0,2,1,0,1,1,0,0
12,"Hawk, Cooper's",0.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,1
13,"Hawk, Northern Goshawk",0.0,0,1,0,0,0,1,0,1,...,0,0,0,1,0,0,0,1,1,0
14,"Hawk, Red-tailed",0.0,0,0,0,1,0,0,1,0,...,5,3,4,1,3,3,0,1,2,2
15,Hawk Species (UH),1.0,0,0,0,0,0,0,1,0,...,0,1,0,0,2,1,0,1,0,0
16,"Pheasant, Ring-necked",0.0,7,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,2,0,0
17,"Grouse, Spruce",0.0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
18,"Grouse, Ruffed",8.0,4,2,5,3,5,4,5,2,...,9,7,3,1,2,1,1,5,0,3
19,"Turkey, Wild",0.0,0,0,0,0,0,0,0,1,...,181,75,6,72,65,116,64,0,75,75
20,"Gull, Ring-billed",0.0,0,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
21,"Gull, Herring",4.0,1,3,1,24,0,0,4,0,...,0,1,0,0,0,0,0,0,0,0
22,"Gull, Great Black-backed",1.0,0,2,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
23,Gull Species (UG),0.0,0,0,0,0,1,0,0,0,...,0,0,1,1,0,0,1,0,0,0
24,"Dove, Mourning",179.0,146,198,250,95,104,171,189,313,...,95,199,218,236,181,129,74,123,100,183
25,"Pigeon, Rock",160.0,71,104,136,60,187,67,80,40,...,122,64,37,87,32,73,20,182,120,111
26,"Owl, Great Horned",0.0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
27,"Owl, Barred",0.0,0,1,0,0,0,0,1,3,...,4,2,0,3,1,1,0,2,1,0
28,"Woodpecker, Red-headed",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
29,"Woodpecker, Red Bellied",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,1
30,"Woodpecker, Downy",62.0,16,19,28,20,45,41,25,34,...,71,43,60,43,35,39,23,28,23,44
31,"Woodpecker, Hairy",39.0,21,26,20,30,22,26,14,30,...,22,34,38,40,39,43,38,40,25,40
32,"Woodpecker, Pileated",6.0,2,5,3,4,1,0,2,4,...,7,4,4,4,7,5,4,3,3,10
33,"Shrike, Northern",1.0,0,0,0,0,0,0,0,3,...,1,0,2,0,0,0,1,0,0,1
34,"Jay, Blue",631.0,191,190,171,154,100,60,176,302,...,152,284,116,47,537,344,70,173,96,288
35,"Jay, Gray",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
36,"Raven, Common",36.0,11,11,12,11,9,17,18,9,...,24,101,25,55,50,34,114,20,34,34
37,"Crow, American",347.0,133,239,302,179,303,64,151,112,...,80,234,167,41,178,111,66,135,111,153
38,"Lark, Horned",25.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
39,Tufted Titmouse,10.0,7,2,8,16,21,28,2,28,...,54,55,53,18,31,32,23,18,28,36
40,"Chickadee, Black-capped",875.0,600,454,669,355,506,555,593,998,...,985,843,731,656,735,488,424,409,362,623
41,"Chickadee, Boreal",0.0,0,0,0,0,0,3,2,0,...,0,0,0,0,0,0,0,0,0,0
42,"Nuthatch, Red-breasted",55.0,31,19,78,47,77,51,53,107,...,152,27,30,16,40,43,24,20,33,36
43,"Nuthatch, White-breasted",80.0,47,8,40,45,48,36,54,125,...,159,63,73,57,59,94,56,38,48,74
44,Brown Creeper,3.0,0,2,2,4,6,7,9,5,...,17,7,9,6,8,5,4,6,1,14
45,"Wren, Carolina",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
46,"Wren, Winter",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
47,"Kinglet, Golden-crowned",10.0,0,1,1,2,36,2,5,1,...,53,9,15,2,8,9,2,42,6,12
48,"Bluebird, Eastern",0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,8,0,0,8,0,4
49,"Robin, American",0.0,0,5,0,0,0,0,0,0,...,2,8,4,0,7,1,0,28,1,14

In [4]:
species = []
year = []
count = []
species_index = []

for i in range(0, len(bird_counts)):
    species_total = 0
    for j in range(1, len(bird_counts.columns)):
        if np.isnan(bird_counts.iloc[i, j]):
            bird_counts.iloc[i, j] = 0
        species_total = int(bird_counts.iloc[i, j]) + species_total
        #if (j == 25):
            #print(species_total)
        

for i in range(0, len(bird_counts)):
    for j in range(1, len(bird_counts.columns)):
        species.append(bird_counts.iloc[i, 0].strip())
        species_index.append(i)
        
        x = datetime.datetime(int(bird_counts.columns[j]), 1, 1)
        
        year.append(x.strftime("%y"))
                    
        count.append(bird_counts.iloc[i, j])
    

bird_counts_dict = {"Species": species, "Year": year, "Count": count, "Species_Index": species_index}
bird_counts_df = pd.DataFrame(bird_counts_dict)

bird_counts_df.to_csv('../data/bird_counts_edited.csv')